### ISSUE TITLE
Where is the lambda code?

### ISSUE THREAD

**Issue by maxerbubba** [maskaravivek/cdk-samples#2]
This line references lambda/ folder but I don't see it
https://github.com/maskaravivek/cdk-samples/blob/main/aws-cdk-s3-lambda-api-gateway/lib/aws-cdk-s3-lambda-api-gateway-stack.ts#L26

**Comment by maskaravivek** [comment]
Hi @maxerbubba! Thanks for reporting. I just pushed the lambda code. 

https://github.com/maskaravivek/cdk-samples/tree/main/aws-cdk-s3-lambda-api-gateway/lambda/s3-authorizer
